"""initial_schema

Revision ID: e27eb129e081
Revises: 
Create Date: 2026-07-05 14:08:10.751329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27eb129e081'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_jobs_created_at', 'ai_jobs', ['created_at'], unique=False)
    op.create_index('ix_ai_jobs_entity_id', 'ai_jobs', ['entity_id'], unique=False)
    op.create_index('ix_ai_jobs_entity_type', 'ai_jobs', ['entity_type'], unique=False)
    op.create_index('ix_ai_jobs_job_type', 'ai_jobs', ['job_type'], unique=False)
    op.create_index('ix_ai_jobs_status', 'ai_jobs', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_url', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_events_slug'),
    sa.UniqueConstraint('source', 'external_id', name='uq_events_source_external_id')
    )
    op.create_index('ix_events_city', 'events', ['city'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_source', 'events', ['source'], unique=False)
    op.create_index('ix_events_starts_at', 'events', ['starts_at'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    op.create_table('hobbies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_hobbies_name'),
    sa.UniqueConstraint('slug', name='uq_hobbies_slug')
    )
    op.create_table('imports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('imported_users', sa.Integer(), nullable=False),
    sa.Column('imported_messages', sa.Integer(), nullable=False),
    sa.Column('skipped_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imports_source', 'imports', ['source'], unique=False)
    op.create_index('ix_imports_started_at', 'imports', ['started_at'], unique=False)
    op.create_index('ix_imports_status', 'imports', ['status'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_interests_name'),
    sa.UniqueConstraint('slug', name='uq_interests_slug')
    )
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_city', 'organizations', ['city'], unique=False)
    op.create_index('ix_organizations_country', 'organizations', ['country'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_settings_key')
    )
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_skills_name'),
    sa.UniqueConstraint('slug', name='uq_skills_slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_users_is_member', 'users', ['is_member'], unique=False)
    op.create_index('ix_users_last_activity_at', 'users', ['last_activity_at'], unique=False)
    op.create_index('ix_users_last_message_at', 'users', ['last_message_at'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('ai_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('growth_areas', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.Text(), nullable=True),
    sa.Column('activity_summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_ai_profiles_user_id')
    )
    op.create_index('ix_ai_profiles_last_analyzed_at', 'ai_profiles', ['last_analyzed_at'], unique=False)
    op.create_index('ix_ai_profiles_user_id', 'ai_profiles', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_changed_by', 'audit_log', ['changed_by'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity_id', 'audit_log', ['entity_id'], unique=False)
    op.create_index('ix_audit_log_entity_type', 'audit_log', ['entity_type'], unique=False)
    op.create_table('event_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_feedback')
    )
    op.create_index('ix_event_feedback_created_at', 'event_feedback', ['created_at'], unique=False)
    op.create_index('ix_event_feedback_event_id', 'event_feedback', ['event_id'], unique=False)
    op.create_index('ix_event_feedback_rating', 'event_feedback', ['rating'], unique=False)
    op.create_index('ix_event_feedback_user_id', 'event_feedback', ['user_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('external_participant_id', sa.String(length=255), nullable=True),
    sa.Column('registration_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consent_personal_data', sa.Boolean(), nullable=False),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('consent_photo', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.BigInteger(), nullable=True),
    sa.Column('ticket_type', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participant')
    )
    op.create_index('ix_event_participants_event_id', 'event_participants', ['event_id'], unique=False)
    op.create_index('ix_event_participants_registered_at', 'event_participants', ['registered_at'], unique=False)
    op.create_index('ix_event_participants_status', 'event_participants', ['status'], unique=False)
    op.create_index('ix_event_participants_user_id', 'event_participants', ['user_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_knowledge_articles_slug')
    )
    op.create_index('ix_knowledge_articles_published_at', 'knowledge_articles', ['published_at'], unique=False)
    op.create_index('ix_knowledge_articles_slug', 'knowledge_articles', ['slug'], unique=False)
    op.create_index('ix_knowledge_articles_status', 'knowledge_articles', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('forwarded_from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('forwarded_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('telegram_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('forwards_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'telegram_message_id', name='uq_messages_chat_message')
    )
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_message_type', 'messages', ['message_type'], unique=False)
    op.create_index('ix_messages_reply_to_message_id', 'messages', ['reply_to_message_id'], unique=False)
    op.create_index('ix_messages_telegram_date', 'messages', ['telegram_date'], unique=False)
    op.create_index('ix_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('behance', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('newsletter_consent', sa.Boolean(), nullable=False),
    sa.Column('personal_data_consent', sa.Boolean(), nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_profiles_user_id')
    )
    op.create_index('ix_profiles_city', 'profiles', ['city'], unique=False)
    op.create_index('ix_profiles_company', 'profiles', ['company'], unique=False)
    op.create_index('ix_profiles_email', 'profiles', ['email'], unique=False)
    op.create_index('ix_profiles_profession', 'profiles', ['profession'], unique=False)
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_table('tag_relations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_relations_entity_id', 'tag_relations', ['entity_id'], unique=False)
    op.create_index('ix_tag_relations_entity_type', 'tag_relations', ['entity_type'], unique=False)
    op.create_index('ix_tag_relations_tag_id', 'tag_relations', ['tag_id'], unique=False)
    op.create_table('timeline',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_created_at', 'timeline', ['created_at'], unique=False)
    op.create_index('ix_timeline_entity_id', 'timeline', ['entity_id'], unique=False)
    op.create_index('ix_timeline_entity_type', 'timeline', ['entity_type'], unique=False)
    op.create_index('ix_timeline_event_type', 'timeline', ['event_type'], unique=False)
    op.create_index('ix_timeline_user_id', 'timeline', ['user_id'], unique=False)
    op.create_table('user_hobbies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hobby_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hobby_id', name='uq_user_hobby')
    )
    op.create_table('user_interests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interest_id', name='uq_user_interest')
    )
    op.create_table('user_organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_organizations_ended_at', 'user_organizations', ['ended_at'], unique=False)
    op.create_index('ix_user_organizations_is_current', 'user_organizations', ['is_current'], unique=False)
    op.create_index('ix_user_organizations_organization_id', 'user_organizations', ['organization_id'], unique=False)
    op.create_index('ix_user_organizations_started_at', 'user_organizations', ['started_at'], unique=False)
    op.create_index('ix_user_organizations_user_id', 'user_organizations', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_article_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_article_id'], ['knowledge_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_sources_article_id', 'knowledge_sources', ['knowledge_article_id'], unique=False)
    op.create_index('ix_knowledge_sources_source_id', 'knowledge_sources', ['source_id'], unique=False)
    op.create_index('ix_knowledge_sources_source_type', 'knowledge_sources', ['source_type'], unique=False)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_article_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_article_id'], ['knowledge_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_article_id', 'tag_name', name='uq_knowledge_article_tag')
    )
    op.create_index('ix_knowledge_tags_article_id', 'knowledge_tags', ['knowledge_article_id'], unique=False)
    op.create_index('ix_knowledge_tags_tag', 'knowledge_tags', ['tag_name'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('telegram_unique_file_id', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('thumbnail_file_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_attachments_attachment_type', 'message_attachments', ['attachment_type'], unique=False)
    op.create_index('ix_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    op.create_index('ix_message_attachments_telegram_unique_file_id', 'message_attachments', ['telegram_unique_file_id'], unique=False)
    op.create_table('saved_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('saved_by', sa.BigInteger(), nullable=True),
    sa.Column('bookmark_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'saved_by', 'bookmark_type', name='uq_saved_messages')
    )
    op.create_index('ix_saved_messages_message_id', 'saved_messages', ['message_id'], unique=False)
    op.create_index('ix_saved_messages_saved_by', 'saved_messages', ['saved_by'], unique=False)
    op.create_index('ix_saved_messages_source', 'saved_messages', ['source'], unique=False)
    op.create_index('ix_saved_messages_status', 'saved_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_messages_status', table_name='saved_messages')
    op.drop_index('ix_saved_messages_source', table_name='saved_messages')
    op.drop_index('ix_saved_messages_saved_by', table_name='saved_messages')
    op.drop_index('ix_saved_messages_message_id', table_name='saved_messages')
    op.drop_table('saved_messages')
    op.drop_index('ix_message_attachments_telegram_unique_file_id', table_name='message_attachments')
    op.drop_index('ix_message_attachments_message_id', table_name='message_attachments')
    op.drop_index('ix_message_attachments_attachment_type', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_knowledge_tags_tag', table_name='knowledge_tags')
    op.drop_index('ix_knowledge_tags_article_id', table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index('ix_knowledge_sources_source_type', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_source_id', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_article_id', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_table('user_skills')
    op.drop_index('ix_user_organizations_user_id', table_name='user_organizations')
    op.drop_index('ix_user_organizations_started_at', table_name='user_organizations')
    op.drop_index('ix_user_organizations_organization_id', table_name='user_organizations')
    op.drop_index('ix_user_organizations_is_current', table_name='user_organizations')
    op.drop_index('ix_user_organizations_ended_at', table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_table('user_interests')
    op.drop_table('user_hobbies')
    op.drop_index('ix_timeline_user_id', table_name='timeline')
    op.drop_index('ix_timeline_event_type', table_name='timeline')
    op.drop_index('ix_timeline_entity_type', table_name='timeline')
    op.drop_index('ix_timeline_entity_id', table_name='timeline')
    op.drop_index('ix_timeline_created_at', table_name='timeline')
    op.drop_table('timeline')
    op.drop_index('ix_tag_relations_tag_id', table_name='tag_relations')
    op.drop_index('ix_tag_relations_entity_type', table_name='tag_relations')
    op.drop_index('ix_tag_relations_entity_id', table_name='tag_relations')
    op.drop_table('tag_relations')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.drop_index('ix_profiles_profession', table_name='profiles')
    op.drop_index('ix_profiles_email', table_name='profiles')
    op.drop_index('ix_profiles_company', table_name='profiles')
    op.drop_index('ix_profiles_city', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_index('ix_messages_thread_id', table_name='messages')
    op.drop_index('ix_messages_telegram_date', table_name='messages')
    op.drop_index('ix_messages_reply_to_message_id', table_name='messages')
    op.drop_index('ix_messages_message_type', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_knowledge_articles_status', table_name='knowledge_articles')
    op.drop_index('ix_knowledge_articles_slug', table_name='knowledge_articles')
    op.drop_index('ix_knowledge_articles_published_at', table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index('ix_event_participants_user_id', table_name='event_participants')
    op.drop_index('ix_event_participants_status', table_name='event_participants')
    op.drop_index('ix_event_participants_registered_at', table_name='event_participants')
    op.drop_index('ix_event_participants_event_id', table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index('ix_event_feedback_user_id', table_name='event_feedback')
    op.drop_index('ix_event_feedback_rating', table_name='event_feedback')
    op.drop_index('ix_event_feedback_event_id', table_name='event_feedback')
    op.drop_index('ix_event_feedback_created_at', table_name='event_feedback')
    op.drop_table('event_feedback')
    op.drop_index('ix_audit_log_entity_type', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_changed_by', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_ai_profiles_user_id', table_name='ai_profiles')
    op.drop_index('ix_ai_profiles_last_analyzed_at', table_name='ai_profiles')
    op.drop_table('ai_profiles')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index('ix_users_last_message_at', table_name='users')
    op.drop_index('ix_users_last_activity_at', table_name='users')
    op.drop_index('ix_users_is_member', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('skills')
    op.drop_table('settings')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index('ix_organizations_country', table_name='organizations')
    op.drop_index('ix_organizations_city', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('interests')
    op.drop_index('ix_imports_status', table_name='imports')
    op.drop_index('ix_imports_started_at', table_name='imports')
    op.drop_index('ix_imports_source', table_name='imports')
    op.drop_table('imports')
    op.drop_table('hobbies')
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_starts_at', table_name='events')
    op.drop_index('ix_events_source', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_city', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_ai_jobs_status', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_job_type', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_entity_type', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_entity_id', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_created_at', table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
